### PR TITLE
docs: configuration of disk-access-mode

### LINKED ISSUE #98: Add docs for `diskAccessMode` field in `onCreation` callback
Explain in more detail how to configure access to the file system.

```js
IncrementalCache.onCreation(() => {
  return {
    diskAccessMode: "read-yes/write-yes”, // and others
  };
});
```

### PR DESCRIPTION
**Pull request by itzsrikanth**
issue: #98 

- Add docs for `diskAccessMode`
- highlighting usage, files involved and a gist of caching mechanism

### CODE REVIEW

**Comment by itzsrikanth** [comment]
I have summarized the content in table for readability and to pack in a nutshell. I am willing to work on a component to replace with the markdown table.

**Comment by better-salmon** [comment]
@itzsrikanth thank you for contributing! I need some time to get into it.

**Comment by better-salmon** [comment]
@itzsrikanth, hello! Your pull request provided valuable insights on cache-handler options. Please wait a little while I make changes to the API 🙏

**Comment by itzsrikanth** [comment]
Thanks a lot for the quick review, pls take your time for changes.
I would be happy to make corresponding changes to the documentation.

**Comment by better-salmon** [comment]
Hi @itzsrikanth, it's been a while since since our last interaction. I appreciate the valuable insights you provided regarding the cache-handler API. After careful consideration, I realized that the `disk-access-mode` option is quite complex and can easily mislead library users. As a result, I spent all this time refactoring the project and creating a new pull request #198. While your original pull request may now be considered obsolete, your contribution has significantly shaped the new one.

I would be grateful if you could review the updated documentation or the code in the new pull request. Your feedback would be invaluable in ensuring the quality and effectiveness of our project. I look forward to your thoughts and suggestions.

**Comment by better-salmon** [comment]
Unfortunately, I must close your pull request because it is obsolete. I appreciate your contribution, and I hope you will continue to contribute in the future. Your contribution has dramatically influenced the refactoring process.

**Pull request closed without merging**
